name: sindbad_management_app
description: "A new Flutter project."
publish_to: "none" 

version: 1.5.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.3.2
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.6
  buttons_tabbar:
  flutter_screenutil:
  flutter_svg:
  google_fonts:
  image_picker: ^1.1.2
  go_router: ^16.2.4
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.2
  flutter_bloc: ^9.1.1
  animated_segmented_tab_control: ^2.0.0
  svg_flutter: ^0.0.1
  barcode_widget: ^2.0.4
  intl: ^0.20.2
  dotted_border: ^2.1.0
  animated_custom_dropdown:
  share_plus: ^11.0.0
  shimmer: ^3.0.0
  open_filex: ^4.3.2
  path_provider:
  pdf:
  printing:
  equatable: ^2.0.7
  device_preview: ^1.2.0
  jwt_decoder: ^2.0.1
  # hive storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  animated_splash_screen: ^1.3.0
  
  flutter_staggered_animations: ^1.1.1

  ### for automatic updates
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1 #
  flutter_file_downloader: ^2.1.0
  flutter_downloader: ^1.11.8 #
  device_info_plus: ^11.2.2 #
  file_picker: ^10.3.6
  url_launcher: ^6.3.2
  shared_preferences: ^2.3.4
  open_folder: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13
  http_mock_adapter: ^0.6.1
  # hive generator fot
  hive_generator: ^2.0.1
 

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/fonts/
    - assets/icons/
    - assets/jsons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          style: italic